#!/usr/bin/env python
"""
Write parquet files from elasticsearch indices, using polars.
"""

from argparse import ArgumentParser, RawDescriptionHelpFormatter
import logging
import requests
import traceback
import re
import json
import sys
from datetime import datetime
from collections import defaultdict

from opensearchpy import OpenSearch, RequestsHttpConnection
import polars as pl

# https://www.elastic.co/guide/en/elasticsearch/reference/6.8/mapping-types.html
# https://docs.pola.rs/py-polars/html/reference/datatypes.html
es2pl_type = {
    'byte': pl.Int8,
    'short': pl.Int16,
    'integer': pl.Int32,
    'long': pl.Int64,
    'half_float': pl.Float32,
    'float': pl.Float32,
    'double': pl.Float64,
    'string': pl.String,
    'text': pl.String,
    'keyword': pl.String,
    'boolean': pl.Boolean,
    'date': pl.Datetime,
    'geo_point': pl.Struct({"lat": pl.Float64, "lon": pl.Float64}),
    'ip': pl.String,
}

logger = logging.getLogger(__name__)

class Processor(object):
    def __init__(self, es, index, output='parquet', compression='uncompressed', sort='@timestamp:asc', size=500, timeout=60, flatten=False, query=None, partition_size=1000, fields=None, cert=None, key=None, verify_certs=True, capath=None):
        self.es = es
        self.index = index
        self.output = output
        self.build_df = self.output in ['parquet', 'ndjson', 'csv']
        self.compression = compression
        self.sort = sort
        self.size = size
        self.timeout = timeout
        self.flatten = flatten
        self.query = query
        self.partition_size = partition_size
        self.fields = fields

        if cert is not None:
            self.es_client = OpenSearch(self.es,
                                        timeout=timeout, 
                                        connection_class = RequestsHttpConnection,
                                        use_ssl = True,
                                        client_cert = cert,
                                        client_key = key,
                                        verify_certs = verify_certs,
                                        ca_certs = capath)
        else:
            self.es_client = OpenSearch(self.es,
                                        timeout=timeout, 
                                        connection_class = RequestsHttpConnection)

        self.doc_warnings = defaultdict(lambda: 0)

    def process(self):
        for idx in self.get_indices(self.index):
            try:
                logger.log(99,'Processing index %s'%idx)
                self.process_index(idx)
            except:
                logger.error('Exception while processing index %s'%idx)
                traceback.print_exc()
                continue

    def map_properties(self, m, prefix=''):
        """Map elasticsearch types to polars types"""
        r={}
        for field,typ in m['properties'].items():
            if 'properties' in typ:
                if self.flatten:
                    r.update(self.map_properties(typ,prefix=field+'_'))
                else:
                    r[prefix+field] = pl.Struct(self.map_properties(typ))
            else:
                r[prefix+field] = es2pl_type.get(typ['type'],None)
                if r[prefix+field] is None:
                    logger.error(f'unhandled es mapping type {typ["type"]} for field {field}')
        return r
    
    def map_source(self, schema, src, prefix=''):
        """Map elasticsearch source doc to native types"""
        dest = {}
        for k, v in src.items():
            pk = prefix+k
            if pk not in schema:
                self.log_warning(f'field {pk} not in schema; dropping')
                continue
                # we really shouldn't be modifying the schema here. Also, we can't stack
                # data frames of different widths, so after the first batch the schema is effectively fixed.
                #try:
                #    dest[pk] = str(v)
                #    schema[pk] = pl.String
                #    self.log_warning(f'field {pk} not in schema, setting to string')
                #except ValueError:
                #    self.log_warning(f'field {pk} not in schema, and can\'t convert to string; dropping')

            # elasticsearch can handle multiple values for a field, without changing the index mapping
            # (it's just the scalar type), while we'd have set the dataframe schema to a list in advance.
            # Taking the first value is an imperfect compromise.
            if type(v) is list:
                if len(v) > 0:
                    self.log_warning(f'field {pk} is list - keeping first value')
                    v = v[0]
                else:
                    continue

            if schema[pk] == pl.Struct:
                if self.flatten:
                    dest.update(self.map_source(schema, v, prefix=k+'_'))
                else:
                    dest[pk] = self.map_source(schema[pk].to_schema(), v)
                continue
            elif schema[pk] == pl.Datetime:
                try:
                    dest[pk] = datetime.fromisoformat(v)
                except ValueError:
                    try:
                        i = int(v)
                        if i < 20000000000:
                            # guess if the epoch number is seconds or milliseconds
                            # if seconds this is Tue Oct 11 07:33:20 EDT 2603
                            # if it's actually millis: Thu Aug 20 07:33:20 EDT 1970
                            # so as long as we don't need to deal with any dates in 1970 
                            # or after the singularity this is fine... even then,
                            # if the date actually is in 1970, the year will at least be correct!
                            dest[pk] = datetime.fromtimestamp(i)
                        else:
                            dest[pk] = datetime.fromtimestamp(i/1000)
                    except ValueError:
                        self.log_warning(f'unable to convert field {pk} to datetime')
            elif schema[pk] in (pl.Int8, pl.Int16, pl.Int32, pl.Int64):
                try:
                    dest[pk] = int(v)
                except ValueError:
                    try:
                        dest[pk] = int(float(v))
                    except ValueError:
                        self.log_warning(f'unable to convert field {pk} to int')
            elif schema[pk] in (pl.Float32, pl.Float64):
                try:
                    dest[pk] = float(v)
                except ValueError:
                    self.log_warning(f'unable to convert field {pk} to float')
            elif schema[pk] == pl.String:
                try:
                    dest[pk] = str(v)
                except ValueError:
                    self.log_warning(f'unable to convert field {pk} to string')
            else:
                dest[pk] = v
        return dest

    def index_schema(self,index):
        mapping = self.es_client.indices.get_mapping(index=index)
        logger.debug(mapping)
        for idx,dts in mapping.items():
            if 'properties' in dts['mappings']:
                # no doc types (ES7+ & OS)
                return self.map_properties(dts['mappings'])
            else:
                # only use the first doc type (multiple doc types were removed in ES5?)
                for dt,m in dts['mappings'].items():
                    return self.map_properties(m)
            return self.map_properties(dts['mappings'])

    def __output_ext(self):
        ext = self.output
        if self.compression == 'gzip':
            ext += '.gz'
        elif self.compression == 'zstd':
            ext += '.zstd'
        return ext

    def process_index(self,index):
        if self.build_df:
            schema = self.index_schema(index)
            logger.debug(schema)
        s = self.es_client.search(index=index,
                                  q=self.query,
                                  _source=self.fields if self.fields else True,
                                  scroll="5m",
                                  size=self.size,
                                  sort=self.sort)
        all_hits = s['hits']['total']
        if type(all_hits) is dict:
            all_hits = all_hits['value']
        if all_hits == 0:
            logger.error('No records found')
            return

        logger.log(99,'Processing %d records'%all_hits)
        partition = 0
        if self.build_df:
            df = pl.DataFrame([self.map_source(schema, d['_source']) for d in s['hits']['hits']], schema=schema, orient='rows')
        elif self.output=='jsonl':
            if all_hits == len(s['hits']['hits']):
                fname = index+'.jsonl'
            else:
                fname = index+f'-{partition:04}.jsonl'
            with open(fname,'w') as f:
                for d in s['hits']['hits']:
                    json.dump(d['_source'], f)
        elif self.output=='stdout':
            for d in s['hits']['hits']:
                json.dump(d['_source'], sys.stdout)
            
        sent_hits = len(s['hits']['hits'])
        logger.info('read %d/%d records'%(sent_hits,all_hits))

        while True:
            try:
                s = self.es_client.scroll(scroll_id=s['_scroll_id'],scroll="5m")
                if len(s['hits']['hits']) == 0:
                    break
                if self.build_df:
                    df2 = pl.DataFrame([self.map_source(schema, d['_source']) for d in s['hits']['hits']], schema=schema, orient='rows')
                    if df is None:
                        df = df2
                    else:
                        df = df.vstack(df2)
                elif self.output=='jsonl':
                    partition += 1
                    fname = index+f'-{partition:04}.jsonl'
                    with open(fname,'w') as f:
                        for d in s['hits']['hits']:
                            json.dump(d['_source'], f)
                elif self.output=='stdout':
                    for d in s['hits']['hits']:
                        json.dump(d['_source'], sys.stdout)
                sent_hits += len(s['hits']['hits'])
                logger.info('read %d/%d records'%(sent_hits,all_hits))

                if self.build_df and df.estimated_size('mb') > 1000:
                    fname = f'{index}-{partition:04}.{self.__output_ext()}'
                    if self.output == 'parquet':
                        df.write_parquet(fname)
                    elif self.output == 'ndjson':
                        df.write_ndjson(fname)
                    elif self.output == 'csv':
                        df.write_csv(fname)
                    logger.log(99,f'Partition size reached. {sent_hits}/{all_hits} records written to {fname}')
                    partition += 1
                    df = None
                    sent_hits = 0
            except KeyboardInterrupt:
                logger.log(99,f'Keyboard interrupt, breaking...')
                break

        for msg,cnt in self.doc_warnings.items():
            logger.warning(f'{msg} [{cnt} documents]')

        if self.build_df:
            if partition == 0:
                fname = f'{index}.{self.__output_ext()}'
            else:
                fname = f'{index}-{partition:04}.{self.__output_ext()}'
            if self.output == 'parquet':
                df.write_parquet(fname)
            elif self.output == 'ndjson':
                df.write_ndjson(fname)
            elif self.output == 'csv':
                df.write_csv(fname)
        elif self.output == 'stdout':
            fname = 'stdout'
        elif self.output == 'jsonl':
            fname = f'{index}*.jsonl'
        logger.log(99,f'Processing complete. {sent_hits}/{all_hits} records written to {fname}.')

    def get_indices(self, index_pattern):
        idxs = self.es_client.indices.get_settings(index=index_pattern)
        return idxs.keys()

    def log_warning(self, msg):
        self.doc_warnings[msg] += 1


if __name__=="__main__":
    parser = ArgumentParser(description='''Dump documents from Elasticsearch or OpenSearch to stdout or files.

Behavior varies with output format:

    parquet: builds a polars dataframe in-memory, accumulating records until the dataframe reaches the 
             specified max partition size, at which point it is written to a parquet file with the index name
             and partition number, which is omitted if the entire results fit into a single parition.
    ndjson:  same as parquet, but written to newline-delimited json files instead.
    csv:     same as parquet, but written to csv files instead.
    stdout:  outputs raw records in JSON format to stdout. Does not attempt to build a dataframe, 
             so will work even if the source data has problematic/inconsistent types.
    jsonl:   same as stdout, but outputs records to files, one per request batch.''',
            formatter_class=RawDescriptionHelpFormatter)
    parser.add_argument('index',help='source index pattern')
    parser.add_argument('--es',help='source cluster address',default="http://localhost:9200")
    parser.add_argument('--cert',help='Client x509 certificate',default=None,type=str)
    parser.add_argument('--key',help='Client x509 key',default=None,type=str)
    parser.add_argument('--no-verify-certs',help='Do not verify x509 certificates',action='store_false')
    parser.add_argument('--capath',help='Path to CA certificates',default=None,type=str)
    # we can just use the index name for each file
    #TODO: hive partitioning? https://duckdb.org/docs/data/partitioning/hive_partitioning
    #parser.add_argument('--filename',help='parquet file name',default="elastic.parquet")
    parser.add_argument('--size',help='Record batch size (default 500)',default=500,type=int)
    parser.add_argument('--sort',help='Comma-separated list of field:direction pairs',default='@timestamp:asc',type=str)
    parser.add_argument('--timeout',help='Elasticsearch read timeout in seconds (default 60)',default=60,type=int)

    parser.add_argument('--output',help='output format',choices=['parquet','ndjson','csv','jsonl','stdout'],default='parquet',type=str)


    parser.add_argument('--flatten',help='Flatten nested data into top level, otherwise use structs',action='store_true')
    parser.add_argument('--query',help='Query string to filter results',default=None,type=str)
    parser.add_argument('--fields',help='Comma-separated list of fields to include in the output. Wildcards are supported. '
                        'Defaults to all fields.',default=None,type=str)
    parser.add_argument('--max-partition-size-mb',help='Maximum in-memory size of partition dataframe in megabytes (default 1000). '
                        'Note that the file size will be smaller due to compression',
                        default=1000,type=int)
    parser.add_argument('--debug',help='Enable debug logging',action='store_true')
    parser.add_argument('--quiet',help='Disable most logging (ignored if --debug specified)',action='store_true')

    args = parser.parse_args()

    logfmt = "%(asctime)s [%(levelname)s %(name)s] %(message)s"
    if args.debug:
        logging.basicConfig(level=logging.DEBUG, format=logfmt)
    elif args.quiet:
        logging.basicConfig(level=logging.ERROR, format=logfmt)
    else:
        logging.basicConfig(level=logging.INFO, format=logfmt)
    logging.addLevelName(99,'UBER')

    processor = Processor(args.es, args.index, 
            output=args.output,
            size=args.size, 
            sort=args.sort,
            timeout=args.timeout, 
            flatten=args.flatten, 
            query=args.query, 
            partition_size=args.max_partition_size_mb, 
            fields=args.fields, 
            cert=args.cert, 
            key=args.key, 
            verify_certs=args.no_verify_certs, 
            capath=args.capath)
    processor.process()
